# Projects configuration
projects:
  devops-opendaoc:
    namespace: devops-opendaoc
    description: "DevOps-OpenDAoC Project"
    sourceRepos:
      - '${ devops_opendaoc_repo }'
    destinations:
      - namespace: prod
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

# Applications configuration
applications:
  opendaoc-database:
    namespace: devops-opendaoc
    project: devops-opendaoc
    source:
      repoURL: '${ devops_opendaoc_repo }'
      path: charts/aws-eks/opendaoc-database
      targetRevision: master
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: prod
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    # Add sync wave annotation
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "0"
          
  opendaoc-core:
    namespace: devops-opendaoc
    project: devops-opendaoc
    source:
      repoURL: '${ devops_opendaoc_repo }'
      path: charts/aws-eks/opendaoc-core
      targetRevision: master
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: prod
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    # Add sync wave annotation
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "1"
