global:
  domain: argocd-devops-opendaoc.gz-42.com

configs:
  params:
    server.insecure: true
  
  applicationset:
    enabled: true
  
  rbac:
    policy.default: role:admin
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, projects, *, *, allow

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true

  config:
    exec.enabled: true