apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-services
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - name: tcp-port
      protocol: TCP
      port: 10300
      targetPort: 10300
