apiVersion: v1
kind: Service
metadata:
  name: mariadb-services
  namespace: gameserver
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  clusterIP: None
  ports:
  - name: mariadb-port
    port: 3306
