apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: gameserver
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
  # Put your own strong password, exemple :
  # echo -n my-secret-pw | base64
