apiVersion: v1
kind: Secret
metadata:
  name: gameserver-secrets
  namespace: gameserver
type: Opaque
data:
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
  # Put your own strong password, exemple :
  # echo -n 'server=mariadb-services.gameserver.svc.cluster.local;port=3306;database=opendaoc;userid=root;password=my-secret-pw;treattinyasboolean=true' | base64
