apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.MARIADB_ROOT_PASSWORD }}
  # echo -n my-secret-pw | base64