apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-services
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  clusterIP: None
  ports:
  - name: {{ .Values.appName }}-port
    port: 3306