name: "Deploy Terraform Infrastructure"

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "yes" to confirm deployment'
        required: true
        type: string

permissions:
  contents: read

jobs:
  security-scan:
    name: "Security Scan"
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_deploy == 'yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          framework: terraform

  terraform-deploy:
    name: "Terraform Deploy"
    needs: security-scan
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_deploy == 'yes' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Create terraform.tfvars
        run: |
          pwd
          ls -larth
          cd terraform
          touch terraform.tfvars
          chmod 644 terraform.tfvars
          cat > terraform.tfvars << EOF
          region = "${{ secrets.AWS_REGION }}"
          project_name = "${{ secrets.PROJECT_NAME }}"
          root_domain_name = "${{ secrets.DOMAIN_NAME }}"
          vpc_cidr = "${{ secrets.VPC_CIDR }}"
          public_subnet_cidrs = ["${{ secrets.VPC_PUBLIC_SUBNETS }}"]
          private_subnet_cidrs = ["${{ secrets.VPC_PRIVATE_SUBNETS }}"]
          cluster_name = "${{ secrets.CLUSTER_NAME }}"
          group_users = ["${{ secrets.GROUP_USERS }}"]
          email = "${{ secrets.EMAIL }}"
          devops_opendaoc_hostname = "${{ secrets.DEVOPS_OPENDAOC_HOSTNAME }}"
          argocd_hostname = "${{ secrets.ARGOCD_HOSTNAME }}"
          mariadb_root_password = "${{ secrets.MARIADB_ROOT_PASSWORD }}"
          db_connection_string = "${{ secrets.DB_CONNECTION_STRING }}"
          grafana_hostname = "${{ secrets.GRAFANA_HOSTNAME }}"
          grafana_pwd = "${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
          slack_webhook = "${{ secrets.SLACK_WEBHOOK }}"
          slack_channel = "${{ secrets.SLACK_CHANNEL }}"
          EOF
          cat terraform.tfvars
          cd tfstate-init
          pwd
          ls -larth
          touch terraform.tfvars
          chmod 644 terraform.tfvars
          cat > terraform.tfvars << EOF
          region = "${{ secrets.AWS_REGION }}"
          prefix = "${{ secrets.TF_STATE_PREFIX }}"
          dynamodb_table_name = "${{ secrets.TF_STATE_KEY }}"
          EOF
          cat terraform.tfvars
          ls -larth
          
      - name: Initialize tfstate infrastructure
        id: init-tfstate
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          cd tfstate
          pwd
          ls -larth
          terraform init
          terraform apply -auto-approve | grep -v "token\|password\|secret\|key\|cert"
          cd ..
          pwd
          ls -larth
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"
            
      - name: Terraform Plan
        id: plan
        env:
          TF_CLI_ARGS: "-compact-warnings"
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          terraform plan -out=tfplan | grep -v "token\|password\|secret\|key\|cert"
          
      - name: Terraform Apply
        env:
          TF_CLI_ARGS: "-compact-warnings"
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          terraform apply -auto-approve tfplan | grep -v "token\|password\|secret\|key\|cert"
      
      - name: Set Load Balancer Hostname Output
        id: set-outputs
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          # Extract the LB hostname from Terraform output (handles sensitive values)
          LB_HOSTNAME=$(terraform output -json | jq -r '.load_balancer_hostname.value')
          
          # Output as a job output (masked in logs if sensitive)
          echo "lb_hostname=$LB_HOSTNAME" >> $GITHUB_OUTPUT
              
      - name: Cleanup sensitive files
        if: always()
        run: |
          pwd
          ls -larth
          cd terraform
          pwd
          ls -larth
          rm -f tfplan
          rm -f crash.log
          rm -f terraform.tfstate*
          rm -f terraform.tfvars
          cd tfstate-init
          rm -r terraform.tfvars
 
  update_dns:
    needs: terraform-deploy
    uses: ./.github/workflows/update-dns-records.yaml
    with:
      lb_hostname: ${{ needs.terraform-deploy.outputs.lb_hostname }}
    secrets: inherit
